### ISSUE TITLE
CGF refinements

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/sienna-locomotive#247]
- [x] Bucketing (instead of just counting the number of hits in the arena, consider the weight of each hit) (#249)
- [x] Make strategies "sticky", i.e. allow a user to specify that the strategy should only be changed after `N` runs that fail to increase coverage. (#248)
- [x] Keep track of which particular strategies caused coverage increases, rather than the relative change in coverage from the prior mutation. (#252)
    - [x] Tell the server how many total strategies there are (see https://github.com/trailofbits/sienna-locomotive/issues/247#issuecomment-413623095) (#251)
