### ISSUE TITLE
Coverage Guided Fuzzing

### ISSUE THREAD

**Issue by TACIXAT** [trailofbits/sienna-locomotive#36]
AFL can be used as an example. Details [here](http://lcamtuf.coredump.cx/afl/technical_details.txt).

```
  if (block_address > elf_text_start && block_address < elf_text_end) {

    cur_location = (block_address >> 4) ^ (block_address << 8);
    shared_mem[cur_location ^ prev_location]++; 
    prev_location = cur_location >> 1;

  }
```

Constrain coverage to a certain module (maybe selectable from wizard?). 

Components/stages:

* [x] Migrate fuzzing calls from server to fuzzing client (#99)
* [x] Refactor events so that the fuzzer registers a crashed run with the server, instead of requesting a mutation from the server and sending a crash status later (#99)
* [x] Build a shared arena that contains basic block (or edge) coverage (#111)
* [x] Use the arena's coverage information to guide the fuzzer's mutation choices (#241)
    * [x] Advise the next generation of fuzz runs based on the most significant coverage change from the previous generation
