### ISSUE TITLE
Open sourcing tasks

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/sienna-locomotive#381]
TODOs for a public release:

- [x] Purge the repo of internal documents, build products, and old (SL1, 1.5) history.
    - [x] Possibly just create a private repo with the original tree and force-push over this one?
- [x] Copy the wiki over to the archive and wipe the one in this repo.
- [x] Rewrite the README (#387).
    - [ ] Logo?
    - [x] Visualization/graphic of SL2's overall structure?
- [x] Set up a CI (#386).
- [x] Set up builds (#386).
- [ ] Provide an initial downloadable and installable version.
- [x] Clean up some of the harness code (we can probably automate some of this). (#382)
- [x] Clean up the DR clients and SL2 server (we can just throw `clang-format` at these). (#383, #385)
- [ ] Freeze the database structure, or come up with a real migration process for updates.
- [x] Mark easy outstanding issues as "help wanted"
- [x] Standardize the DR client names (`fuzz_dynamorio` should be `fuzzer`, `tracer_dynamorio` should be `tracer`) (#388)
- [x] Scrub references to `fuzzkit` and other pre-alpha names (#389).
- [ ] Build the DR clients/triage tools as Release, not Debug.
- [x] Automatic cronbuilds, a la DynamoRIO
    - Travis's support for WIndows deployments is still a little immature, so this will probably have to wait for a bit. (Broken out as #390)
